
import javax.swing.*;
import java.awt.CardLayout;

public class TampilGambar extends JFrame {

    public TampilGambar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFlutter = new javax.swing.JButton();
        btnAI = new javax.swing.JButton();
        btnPython = new javax.swing.JButton();
        cover = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFlutter.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnFlutter.setText("FLUTTER");
        btnFlutter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlutterActionPerformed(evt);
            }
        });

        btnAI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnAI.setText("AI");
        btnAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAIActionPerformed(evt);
            }
        });

        btnPython.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnPython.setText("PYTHON");
        btnPython.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPythonActionPerformed(evt);
            }
        });

        cover.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFlutter, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAI, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPython))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cover, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAI, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPython, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFlutter, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cover, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAIActionPerformed
        // TODO add your handling code here:
        showImage("D:\\RANDA\\PenampilGambar\\AI.jpeg");
    }//GEN-LAST:event_btnAIActionPerformed

    private void btnFlutterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlutterActionPerformed
        // TODO add your handling code here:
        showImage("D:\\RANDA\\PenampilGambar\\FLUTTER.jpeg");
    }//GEN-LAST:event_btnFlutterActionPerformed

    private void btnPythonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPythonActionPerformed
        // TODO add your handling code here:
        showImage("D:\\RANDA\\PenampilGambar\\PYTHON.jpeg");
    }//GEN-LAST:event_btnPythonActionPerformed

    private void showImage(String imagePath) {
        try {
            ImageIcon icon = new ImageIcon(imagePath);
            JLabel imageLabel = new JLabel(icon);
            cover.removeAll();
            cover.add(imageLabel);
            CardLayout cardLayout = (CardLayout) cover.getLayout();
            cardLayout.show(cover, "Image");
            cover.revalidate();
            cover.repaint();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading image: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilGambar().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAI;
    private javax.swing.JButton btnFlutter;
    private javax.swing.JButton btnPython;
    private javax.swing.JPanel cover;
    // End of variables declaration//GEN-END:variables
}
